### ISSUE TITLE
Misleading info in error message concerning invalid path to VEP-cache

### ISSUE THREAD

**Issue by asp8200** [nf-core/sarek#1326]
### Description of the bug

Observed on Sarek 3.3.2 (and on dev 51c7676c0947849d191359bf2c66bf32b10dc88b) :

The error message for invalid VEP-cache contains some seeming misleading info about invalid sample-sheet.
```
The sample-sheet only contains tumor-samples, but the following tools, which were requested by the option "tools", expect at least one normal-sample : ascat
The sample-sheet only contains normal-samples, but the following tools, which were requested with "--tools", expect at least one tumor-sample : ascat, controlfreec, mutect2
Path provided with VEP cache is invalid.
Make sure there is a directory named homo_sapiens/110_GRCh38 in /home/ubuntu/dev/./nPlease refer to https://nf-co.re/sarek/docs/usage/#how-to-customise-snpeff-and-vep-annotation for more information.
```
My guess is that the lines about the invalid sample-sheet comes from nf-validation.

### Command used and terminal output

```console
nextflow run main.nf -profile test_full,docker --vep_cache /some/invalid/path --outdir foo
```

**Comment by FriederikeHanssen** [comment]
Canyou check whether this is still relevant on dev? Pretty sure a bunch of stuff was fixed around this

**Comment by FriederikeHanssen** [comment]
OK found the corresponding slack thread, and it is also present on dev

**Comment by asp8200** [comment]
> Canyou check whether this is still relevant on dev? Pretty sure a bunch of stuff was fixed around this

I also wrote in the description that I check it on `dev`.

**Comment by bounlu** [comment]
I confirm that this issue still persists in version `3.4.3`.
